name: Shellcheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: shellcheck -e SC2006 ./*/*.sh

